import manifest from '../data/images.json'

type Manifest = Record<string, { width: number; height: number; widths: number[] }>
const images = manifest as Manifest

type Props = {
  slug: string
  alt: string
  sizes: string
  priority?: boolean
  className?: string
}

/** Responsive AVIF/WebP picture generated by scripts/images.ts. */
export function Picture({ slug, alt, sizes, priority, className }: Props) {
  const img = images[slug]
  if (!img) {
    return (
      <div
        className={className}
        aria-label={alt}
        role="img"
        style={{ aspectRatio: '1 / 1', background: 'var(--board-2)' }}
      />
    )
  }
  const srcset = (ext: string) => img.widths.map(w => `/img/${slug}-${w}.${ext} ${w}w`).join(', ')
  const fallback = img.widths.includes(1024) ? 1024 : img.widths[img.widths.length - 1]
  return (
    <picture className={className}>
      <source type="image/avif" srcSet={srcset('avif')} sizes={sizes} />
      <img
        src={`/img/${slug}-${fallback}.webp`}
        srcSet={srcset('webp')}
        sizes={sizes}
        width={img.width}
        height={img.height}
        alt={alt}
        loading={priority ? 'eager' : 'lazy'}
        decoding={priority ? 'sync' : 'async'}
        fetchPriority={priority ? 'high' : 'auto'}
      />
    </picture>
  )
}
